import {useState,type FormEvent} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {services,packages} from './content';
import './contact-page.css';

// Temporary contact details: reserved example email and Ofcom fictional UK numbers.
const contactDetails={email:'hello@asterdigital.example',phone:'+44 20 7946 0123',whatsapp:'+44 7700 900123',location:'United Kingdom',hours:'Mon–Fri, 09:00–18:00',timezone:'UK time · GMT / BST'};
function ContactIcon({kind}:{kind:string}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind==='email'?<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/></>:kind==='phone'?<path d="m5 3 4 1 1 5-3 2c2 3 3 4 6 6l2-3 5 1 1 4c-1 5-9 1-13-3S0 4 5 3Z"/>:kind==='location'?<><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/></>:kind==='hours'?<><circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/></>:<path d="M21 11a9 9 0 0 1-9 9H4l-2 2V11a9 9 0 1 1 19 0Z"/>}</svg>}
export default function ContactPage(){
 const [params]=useSearchParams();const [errors,setErrors]=useState<Record<string,string>>({});const [summary,setSummary]=useState<Record<string,string>|null>(null);const pre=params.get('service')||'';
 const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const data=Object.fromEntries(new FormData(form)) as Record<string,string>;const next:Record<string,string>={};if(!data.name.trim())next.name='Please enter your full name.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email.trim()))next.email='Please enter a valid email address.';if(!data.description.trim())next.description='Please tell us about your project.';setErrors(next);if(Object.keys(next).length){setSummary(null);(form.elements.namedItem(Object.keys(next)[0]) as HTMLElement)?.focus();return}setSummary(data)};
 return <div className="uk-contact-page"><header className="wrap uk-contact-heading"><p className="eyebrow">START A CONVERSATION</p><h1>Tell us about<br/>your next chapter.</h1><p>A new website, a stronger brand, or a clearer direction. Let’s talk about what your business needs.</p></header><div className="wrap uk-contact-grid">
 <section className="uk-form-panel" aria-labelledby="contact-form-title"><h2 id="contact-form-title">Send us a message</h2><p className="uk-form-intro">Share your plans and we’ll help define the next step.</p><form noValidate onSubmit={submit} onChange={()=>setSummary(null)}>
 <div className="uk-field-grid">{[['name','Full name','text','Alex Taylor','name'],['email','Email','email','alex@example.com','email'],['phone','Phone','tel','+44 7700 900123','tel'],['company','Company','text','Your company','organization']].map(([id,label,type,placeholder,auto])=><label key={id} htmlFor={'uk-'+id}>{label}{['name','email'].includes(id)&&<span className="uk-required"> *</span>}<input id={'uk-'+id} name={id} type={type} placeholder={placeholder} autoComplete={auto} required={['name','email'].includes(id)} aria-invalid={!!errors[id]} aria-describedby={errors[id]?'uk-error-'+id:undefined}/>{errors[id]&&<span className="uk-error" id={'uk-error-'+id}>{errors[id]}</span>}</label>)}
 <label>Service<select name="service" defaultValue={pre}><option value="">Select a service</option>{pre&&!services.some(s=>s.name===pre)&&<option>{pre}</option>}{services.map(s=><option key={s.slug}>{s.name}</option>)}</select></label><label>Budget (GBP)<select name="budget"><option>Let’s discuss</option><option>Under £1,000</option><option>£1,000–£3,000</option><option>£3,000–£5,000</option><option>£5,000–£10,000</option><option>£10,000+</option></select></label>
 <label>Ideal timeline<select name="timeline"><option>Flexible / exploring</option><option>Within 1 month</option><option>1–3 months</option><option>3+ months</option></select></label><label>Package interest<select name="package" defaultValue={params.get('package')||''}><option value="">Not sure yet</option>{[...packages,'Custom'].map(p=><option key={p}>{p}</option>)}</select></label></div>
 {params.get('industry')&&<label>Industry<input name="industry" defaultValue={params.get('industry')||''}/></label>}
 <label htmlFor="uk-description">Message<span className="uk-required"> *</span><textarea id="uk-description" name="description" rows={5} placeholder="Tell us about your project…" required aria-invalid={!!errors.description} aria-describedby={errors.description?'uk-error-description':undefined}/>{errors.description&&<span className="uk-error" id="uk-error-description">{errors.description}</span>}</label>
 <p className="uk-form-note">Local preview: your enquiry is reviewed here, not sent or saved. Budgets are in pounds sterling (GBP). <Link to="/privacy">Privacy information</Link>.</p><button type="submit" className="uk-submit">Review your enquiry <span aria-hidden="true">→</span></button>
 {summary&&<section className="uk-enquiry-summary" role="status"><h3>Your enquiry preview</h3><p>No message has been sent.</p><dl>{[['name','Name'],['email','Email'],['service','Service'],['budget','Budget (GBP)'],['description','Message']].map(([key,label])=><div key={key}><dt>{label}</dt><dd>{summary[key]||'Not specified'}</dd></div>)}</dl><button type="button" onClick={()=>setSummary(null)}>Continue editing</button></section>}
 </form></section>
 <aside className="uk-contact-cards" aria-label="Contact information">{[['email','Email us',contactDetails.email,'Sample email'],['phone','Call us',contactDetails.phone,'Sample UK telephone'],['location','Location',contactDetails.location,'Serving businesses across the UK'],['hours','Working hours',contactDetails.hours,contactDetails.timezone]].map(([kind,label,value,note])=><div className="uk-info-card" key={kind}><span className={'uk-contact-icon '+kind}><ContactIcon kind={kind}/></span><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></div>)}
 <div className="uk-whatsapp-card"><span className="uk-contact-icon whatsapp"><ContactIcon kind="chat"/></span><div><p>Chat on WhatsApp</p><strong>{contactDetails.whatsapp}</strong><small>Sample number · connection coming soon</small></div></div><p className="uk-contact-note">Temporary contact details for this preview. Real email, telephone, and WhatsApp details will be added before launch.</p>
 </aside></div></div>
}
