import Service from './service-detail-page';
import Services from './services-page';
import Contact from './contact-page';
import PreFooterCTA from './pre-footer-cta';
import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route,Link,NavLink,useLocation,useParams,useSearchParams} from 'react-router-dom';
import {brand,groups,services,projects,faqs,articles,industries,packages,slugify} from './content';
import Home from './home';
import {SiteNavigation,ServiceShowcase} from './service-components';
import {serviceCategories} from './content';
import './style.css';
import './refined.css';
import './charcoal-theme.css';
Object.entries({paper:brand.colors.ivory,ink:brand.colors.ink,green:brand.colors.green,accent:brand.colors.accent}).forEach(([key,value])=>document.documentElement.style.setProperty('--'+key,value));
const Arrow=()=> <span aria-hidden="true">↗</span>;
function Button({to='/contact',children,secondary=false}:{to?:string,children:React.ReactNode,secondary?:boolean}){return <Link className={secondary?'text-link':'button'} to={to}>{children}<Arrow/></Link>}
function Title({eyebrow,title,description}:{eyebrow:string,title:string,description?:string}){return <header className="page-title"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description&&<p className="lede">{description}</p>}</header>}
function Layout(){const loc=useLocation();useEffect(()=>{window.scrollTo(0,0);const key=loc.pathname.split('/').filter(Boolean).at(-1);document.title=key?`${key.split('-').map(x=>x[0]?.toUpperCase()+x.slice(1)).join(' ')} | ${brand.name}`:`${brand.name} — Make room for growth`;document.querySelector('meta[name="description"]')?.setAttribute('content',key?`Explore ${key.replace(/-/g,' ')} with ${brand.name}. ${brand.description}`:brand.description)},[loc.pathname]);return <><a className="skip" href="#main">Skip to content</a><SiteNavigation/><main id="main" tabIndex={-1}><Routes><Route path="/" element={<Home/>}/><Route path="/services" element={<Services/>}/><Route path="/services/:slug" element={<Service/>}/><Route path="/about" element={<About/>}/><Route path="/work" element={<Work/>}/><Route path="/work/:slug" element={<Project/>}/><Route path="/pricing" element={<Pricing/>}/><Route path="/industries" element={<Industries/>}/><Route path="/industries/:slug" element={<Industry/>}/><Route path="/resources" element={<Resources/>}/><Route path="/resources/:slug" element={<Article/>}/><Route path="/contact" element={<Contact/>}/><Route path="/audit" element={<Audit/>}/><Route path="/faq" element={<div className="wrap"><Title eyebrow="A little clarity" title="Good questions. Honest answers."/><FAQ/></div>}/><Route path="/process" element={<div className="wrap"><Title eyebrow="How we work" title="Clear steps. Shared direction."/><Process/></div>}/><Route path="/privacy" element={<Legal type="Privacy"/>}/><Route path="/terms" element={<Legal type="Terms"/>}/><Route path="/careers" element={<Simple type="careers"/>}/><Route path="/client-preview" element={<Simple type="portal"/>}/><Route path="/sitemap" element={<Sitemap/>}/><Route path="*" element={<NotFound/>}/></Routes></main>{(loc.pathname==='/'||loc.pathname==='/services')&&<PreFooterCTA/>}<Footer/></>}
function ProjectGrid({items=projects}:{items?:typeof projects}){return <div className="project-grid">{items.map(p=><Link className="project-card" to={'/work/'+p.slug} key={p.slug}><div className="project-visual" style={{background:p.color}}><div className={'mini-site '+p.slug}><div className="mini-nav"><b>{p.name}</b><span>ABOUT &nbsp; COLLECTION</span></div><div className="mini-content"><small>{p.industry}</small><h3>{p.line}</h3><img src={p.image} alt={`${p.name} concept art direction`} loading="lazy"/></div></div><span className="project-open"><Arrow/></span></div><div className="project-meta"><div><h3>{p.name}</h3><p>{p.category} · {p.industry}</p></div><small>CONCEPT PROJECT</small></div></Link>)}</div>}
function Process(){return <div className="process-grid">{[['Listen','We get to know your business, your audience, and where you want to go.'],['Find the direction','We agree on the priorities, scope, and creative direction before building.'],['Make it happen','Design, content, and development come together with room for your feedback.'],['Keep growing','A clear handover and support plan help you take the next step confidently.']].map(([t,p],i)=><div key={t}><span className="step">0{i+1}</span><h3>{t}</h3><p>{p}</p></div>)}</div>}
function FAQ({limit=6,items=faqs}:{limit?:number,items?:string[][]}){return <div className="faq">{items.slice(0,limit).map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div>}
function CTA(){return <section className="cta"><div className="wrap"><p className="eyebrow">LET’S MAKE SOMETHING MEANINGFUL</p><h2>What’s your<br/><em>next chapter?</em></h2><p>A new idea. A fresh start. A better way forward.<br/>We’d love to hear what you have in mind.</p><Button>Let’s talk about it</Button><span className="cta-star" aria-hidden="true">✳</span></div></section>}
function Filters({items,value,onChange}:{items:string[],value:string,onChange:(v:string)=>void}){return <div className="filters" aria-label="Filter options">{items.map(x=><button key={x} aria-pressed={value===x} onClick={()=>onChange(x)}>{x}</button>)}</div>}
function Crumb({parent,to,current}:{parent:string,to:string,current:string}){return <nav className="breadcrumbs" aria-label="Breadcrumb"><Link to={to}>{parent}</Link><span>/</span><span>{current}</span></nav>}
function Work(){const [cat,setCat]=useState('All work');return <div className="wrap"><Title eyebrow="Selected possibilities" title="Good ideas, thoughtfully brought to life." description="Original concept projects that show a direction, a way of thinking, and the details that bring it together. These are not client commissions."/><Filters items={['All work',...projects.map(p=>p.category)]} value={cat} onChange={setCat}/><p role="status" className="result-note">{projects.filter(p=>cat==='All work'||p.category===cat).length} concept projects</p><ProjectGrid items={projects.filter(p=>cat==='All work'||p.category===cat)}/><CTA/></div>}
function Project(){const {slug}=useParams();const p=projects.find(p=>p.slug===slug);if(!p)return <NotFound/>;return <><div className="wrap"><Crumb to="/work" parent="Our work" current={p.name}/><Title eyebrow={'Concept project / '+p.industry} title={p.name} description={p.line}/><img className="case-image" src={p.image} alt={`${p.name} photographic art direction`}/><section className="section split"><div><p className="eyebrow">THE BRIEF</p><h2>{p.line}</h2><p>{p.brief}</p></div><div><h3>The approach</h3><p>{p.approach}</p><h3>Proposed deliverables</h3><ul>{p.deliverables.map(x=><li key={x}>{x}</li>)}</ul><p className="note">Original fictional project. Photography is licensed stock. No client relationship or performance result is implied.</p></div></section><ProjectGrid items={projects.filter(x=>x.slug!==slug)}/></div><CTA/></>}
function About(){return <><div className="wrap"><Title eyebrow="Meet Aster" title="Thoughtful by nature. Collaborative by design." description="Aster Digital is a working agency identity for a team that brings strategy, design, and development into the same conversation."/><div className="about-image"><img src="/assets/studio.jpg" alt="Light-filled studio with a desk and artwork"/><p>Room for ideas.<br/><em>Space to grow.</em></p></div><section className="section split"><h2>Your business deserves<br/><em>to be understood.</em></h2><div><p>Our proposed approach is simple: listen closely, make decisions with purpose, and create things people can use. We value a clear explanation as much as a considered design.</p><p>We’re shaping this studio around businesses in Pakistan and beyond, with a process that makes collaboration feel approachable.</p><p className="note">Aster Digital is a placeholder identity. Company history, credentials, and team biographies await real client information.</p></div></section><div className="process-grid">{['Clarity over complexity','Care in the details','Honest collaboration','Room to evolve'].map((v,i)=><div key={v}><span className="step">0{i+1}</span><h3>{v}</h3><p>{['A shared brief and plain language keep everyone moving in the same direction.','Typography, usability, and handover deserve the same attention as the big idea.','Realistic scope and open feedback make better work possible.','Build a foundation that can adapt as the business finds its next step.'][i]}</p></div>)}</div><section className="section"><p className="eyebrow">THE PEOPLE BEHIND THE PROCESS</p><h2>Different disciplines.<br/>A shared direction.</h2><div className="team">{['Strategy & client experience','Design & content','Development & support'].map((x,i)=><article key={x}><span className="team-mark">0{i+1}</span><h3>{x}</h3><p>Team profile to be introduced.</p></article>)}</div><div className="proof"><h3>Real proof belongs here.</h3><p>Client stories, approved testimonials, and verified recognition will be added when supplied. For now, explore our clearly labeled concept work.</p><Button to="/work" secondary>See the concepts</Button></div></section></div><CTA/></>}
function Pricing(){const [category,setCategory]=useState('Web & commerce');return <div className="wrap"><Title eyebrow="Ways to work together" title="The right scope. A clear starting point." description="Flexible package outlines to start the conversation. Final deliverables, timelines, and pricing are agreed around your business."/><Filters items={groups.slice(1)} value={category} onChange={setCategory}/><div className="pricing-grid">{packages.map((p,i)=><article className={i===1?'price-card featured':'price-card'} key={p}><p className="eyebrow">0{i+1} / {category}</p><h2>{p}</h2><p>{['A focused first step with a well-defined outcome.','A connected set of deliverables for your next chapter.','Ongoing attention as your priorities evolve.'][i]}</p><h3>Request pricing</h3><ul>{[category+' discovery',...services.find(s=>s.group===category)!.items.slice(0,i+2),['Handover notes','Connected launch plan','Ongoing review schedule'][i]].map(x=><li key={x}>{x}</li>)}</ul><Button to={'/contact?service='+encodeURIComponent(category)+'&package='+p}>Explore {p}</Button></article>)}</div><section className="section"><h2>Compare the approach.</h2><div className="table-scroll"><table><caption>Proposed package structure — all details subject to agreement</caption><thead><tr><th>Included approach</th>{packages.map(p=><th key={p}>{p}</th>)}</tr></thead><tbody>{[['Discovery','Focused','Expanded','Ongoing'],['Scope','Single priority','Connected priorities','Evolving roadmap'],['Review','Milestone review','Milestone reviews','Regular reviews'],['Handover','Documentation','Documentation & training','Continuous support planning']].map(row=><tr key={row[0]}>{row.map((c,i)=>i===0?<th key={c} scope="row">{c}</th>:<td key={i}>{c}</td>)}</tr>)}</tbody></table></div></section><div className="proof"><h2>Something a little different?</h2><p>Tell us what you’re imagining. We can shape a custom scope around it.</p><Button to="/contact?package=Custom">Build a custom brief</Button></div><FAQ/></div>}
function Industries(){return <div className="wrap"><Title eyebrow="Your world, understood" title="Different businesses. Different possibilities." description="Explore starting points for your industry. These are proposed solutions, not claims of past sector experience."/><div className="industry-grid">{industries.map((x,i)=><Link key={x} to={'/industries/'+slugify(x)}><span>{String(i+1).padStart(2,'0')}</span><h2>{x}</h2><Arrow/></Link>)}</div><CTA/></div>}
function Industry(){const {slug}=useParams();const name=industries.find(x=>slugify(x)===slug);if(!name)return <NotFound/>;return <div className="wrap"><Crumb parent="Industries" to="/industries" current={name}/><Title eyebrow="Industry possibilities" title={name} description={`A clear digital presence starts with understanding how people choose a ${name.toLowerCase()} business.`}/><div className="split section"><div><h2>Make the next step feel natural.</h2><p>Help visitors understand your offering, find relevant information, and decide whether to get in touch. The first conversation will identify your customers’ questions and the information they need.</p><Button to={'/contact?industry='+encodeURIComponent(name)}>Discuss your business</Button></div><div><h3>A practical starting point</h3><ul><li>Clear service or product information</li><li>Mobile-friendly discovery and enquiry</li><li>Relevant stories and useful resources</li><li>A content plan your team can maintain</li></ul><Button to="/services" secondary>Find your services</Button></div></div></div>}
function Resources(){const [cat,setCat]=useState('All topics');const [q,setQ]=useState('');const filtered=articles.filter(a=>(cat==='All topics'||a.category===cat)&&(a.title+' '+a.intro).toLowerCase().includes(q.toLowerCase()));return <div className="wrap"><Title eyebrow="The Aster journal" title="A little perspective for your next move." description="Practical notes on websites, brands, and doing digital with more intention. Original sample editorial content."/><div className="resource-controls"><Filters items={['All topics','Web design','Ecommerce','Marketing']} value={cat} onChange={setCat}/><label className="search">Search the journal<input type="search" placeholder="What’s on your mind?" value={q} onChange={e=>setQ(e.target.value)}/></label></div><p className="result-note" role="status">{filtered.length} articles found</p><div className="article-grid">{filtered.map((a)=><Link to={'/resources/'+a.slug} key={a.slug}><div className="article-art"><span>{a.category}</span><h2>{a.title}</h2><Arrow/></div><small>{a.read} · Sample article</small><p>{a.intro}</p><span className="text-link">Read the story <Arrow/></span></Link>)}</div>{!filtered.length&&<div className="empty"><h2>No stories found.</h2><p>Try a broader search or another topic.</p><button className="button" onClick={()=>{setQ('');setCat('All topics')}}>Clear filters</button></div>}<div className="proof"><p className="eyebrow">A FRESH PAIR OF EYES</p><h2>Not sure where to begin?</h2><p>Explore a sample website review to understand what an initial audit could cover.</p><Button to="/audit" secondary>Explore the website review</Button></div><Newsletter/></div>}
function Article(){const {slug}=useParams();const a=articles.find(a=>a.slug===slug);if(!a)return <NotFound/>;return <article className="wrap reading"><Crumb parent="Journal" to="/resources" current={a.category}/><Title eyebrow={`${a.category} / ${a.read} / Sample article`} title={a.title} description={a.intro}/>{a.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}<div className="proof"><h3>Turn a useful idea into a next step.</h3><Button>Tell us what you’re planning</Button></div><Button to="/resources" secondary>Back to the journal</Button></article>}
function Newsletter(){const [done,setDone]=useState(false);return <section className="newsletter"><div><p className="eyebrow">LET GOOD IDEAS FIND YOU</p><h2>Notes from the studio.</h2><p>Newsletter preview. Subscriptions are not connected yet.</p></div><form onSubmit={e=>{e.preventDefault();setDone(true)}}><label htmlFor="newsletter-email">Your email</label><div className="inline-form"><input id="newsletter-email" type="email" required placeholder="you@yourbusiness.com"/><button className="button">Preview signup <Arrow/></button></div>{done&&<p role="status">Preview complete. You have not been subscribed.</p>}</form></section>}
function Audit(){const [shown,setShown]=useState(false);return <div className="wrap"><Title eyebrow="A fresh perspective" title="See your website with fresh eyes." description="Explore the questions behind a useful website review. This sample does not scan or score a live website."/><div className="split section"><div><h2>Clarity before a redesign.</h2><p>A first review can look at your message, navigation, mobile experience, and enquiry path. It is a starting point for a conversation, not an automated verdict.</p><button className="button" aria-expanded={shown} onClick={()=>setShown(!shown)}>{shown?'Hide sample review':'Open sample review'} <Arrow/></button><p><Button to="/contact?service=Website%20review" secondary>Request a website review</Button></p></div><div>{shown?<div className="proof" role="region" aria-label="Sample website review"><p className="eyebrow">ILLUSTRATIVE REVIEW — NO LIVE SCAN</p><h3>Fictional small-business website</h3>{[['Message','Make the main service and audience clear in the first screen.'],['Navigation','Group related services and use familiar labels.'],['Mobile','Check button spacing and form labels on a small screen.'],['Enquiry','Explain what happens after someone gets in touch.']].map(([h,p])=><div key={h}><h4>{h}</h4><p>{p}</p></div>)}</div>:<div className="audit-placeholder"><span>01 — 04</span><h2>Message.<br/>Journey.<br/>Experience.<br/><em>Next step.</em></h2></div>}</div></div></div>}
function Legal({type}:{type:string}){return <div className="wrap reading"><Title eyebrow="Draft — client review required" title={`${type} notice`} description="This is a prototype notice, not an approved legal policy. Replace it with a policy reflecting the real business before publication."/>{type==='Privacy'?<><h2>What this preview does</h2><p>The local enquiry and newsletter forms validate entries in your browser. They do not send information to a server, subscribe you, or persist your entries after a refresh.</p><h2>Tracking and assets</h2><p>This prototype has no analytics, advertising cookies, or tracking integrations. Photographs are served from local project assets.</p><h2>Before publication</h2><p>Confirm the business identity, contact details, actual processors, data uses, retention periods, rights process, and applicable jurisdictions. Review the final implementation alongside the policy.</p></>:<><h2>Demonstration status</h2><p>Aster Digital is a working identity. Services and packages are provisional, and concept projects are fictional examples. Nothing here establishes a commercial offer or service agreement.</p><h2>Project agreements</h2><p>A real engagement needs an agreed scope, commercial terms, responsibilities, intellectual property provisions, and support arrangements.</p><h2>Content and third-party assets</h2><p>Project copy and the placeholder identity were created for this prototype. Photography is licensed separately; attribution details are included in the project documentation.</p></>}</div>}
function Simple({type}:{type:string}){return <div className="wrap"><Title eyebrow={type==='careers'?'Work with us':'Client experience preview'} title={type==='careers'?'Good work starts with good people.':'A little clarity, all in one place.'} description={type==='careers'?'There are no confirmed vacancies at this stage. The studio identity and team structure are still provisional.':'An illustrative view of how a future client space might organise a project. No login, billing, hosting access, or support system is connected.'}/>{type==='portal'&&<div className="directory">{['Project scope & milestones','Documents & handover','Hosting & domain overview','Invoices & support requests'].map(x=><article className="proof" key={x}><h2>{x}</h2><p>Demonstration only. Real records and actions require a secure backend.</p></article>)}</div>}<Button>Start a conversation</Button></div>}
function Sitemap(){return <div className="wrap"><Title eyebrow="Find your way" title="A place for everything."/><div className="sitemap">{[['/','Home'],['/about','About'],['/services','Services'],['/work','Work'],['/pricing','Packages'],['/industries','Industries'],['/resources','Journal'],['/audit','Website review'],['/process','Process'],['/faq','FAQs'],['/careers','Careers'],['/client-preview','Client preview'],['/privacy','Privacy'],['/terms','Terms'],['/contact','Contact'],...services.map(s=>['/services/'+s.slug,s.name]),...projects.map(p=>['/work/'+p.slug,p.name]),...industries.map(i=>['/industries/'+slugify(i),i]),...articles.map(a=>['/resources/'+a.slug,a.title])].map(([url,n])=><Link key={url} to={url}>{n} ↗</Link>)}</div></div>}
function NotFound(){return <div className="wrap not-found"><p className="eyebrow">404 / A LITTLE OFF THE PATH</p><h1>Let’s find your<br/><em>way back.</em></h1><p>The page you’re looking for isn’t here. There’s plenty to explore from the beginning.</p><Button to="/">Back to home</Button></div>}
function Footer(){return <footer className="footer"><div className="wrap footer-grid"><div><Link className="logo" to="/"><img className="wordmark" src={brand.wordmark} alt={brand.name}/></Link><p>{brand.tagline}<br/>{brand.region}</p></div><div><h3>Explore</h3>{[['/services','Services'],['/work','Our work'],['/pricing','Packages'],['/industries','Industries']].map(([u,t])=><Link key={u} to={u}>{t}</Link>)}</div><div><h3>The studio</h3>{[['/about','About us'],['/process','Our process'],['/resources','Journal'],['/careers','Careers']].map(([u,t])=><Link key={u} to={u}>{t}</Link>)}</div><div><h3>A little help</h3>{[['/contact','Start a project'],['/audit','Website review'],['/faq','FAQs'],['/client-preview','Client preview']].map(([u,t])=><Link key={u} to={u}>{t}</Link>)}</div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} {brand.name} · An agency concept</span><div><Link to="/privacy">Privacy (draft)</Link><Link to="/terms">Terms (draft)</Link><Link to="/sitemap">Sitemap</Link><a href="#main">Back to top ↑</a></div></div></footer>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><Layout/></BrowserRouter></React.StrictMode>);







