import {services,serviceCategories} from './content';
export type Service = typeof services[number];
type Editorial = {headline:string;intro:string;details:[string,string,string,string];need:string};

export const serviceEditorial:Record<string,Editorial>={
 'web-design-and-development':{headline:'Build a website that works as hard as your business.',intro:'Your website should help people understand what you do, trust your business, and take the next step. We plan the pages, content, and enquiry journey around the people you want to reach.',details:['Define your audience, organise the pages, and make important information easy to find.','Create layouts that work comfortably on phones, tablets, and desktop screens.','Build clear navigation, readable content, and keyboard-friendly interactions.','Review forms, metadata, page performance, and content before your website goes live.'],need:'Need a website for your business?'},
 ecommerce:{headline:'Turn product discovery into a better shopping experience.',intro:'A successful store starts with useful product information and a clear route to purchase. We shape browsing, collections, and checkout around your catalogue and day-to-day operations.',details:['Organise products, variants, and filters so shoppers can compare their options.','Create consistent product and collection pages that work across screen sizes.','Plan payment, delivery, and checkout requirements for your UK customers.','Document how to add products, manage collections, and maintain your catalogue.'],need:'Ready to build your online store?'},
 wordpress:{headline:'A WordPress website your team can make its own.',intro:'Bring your content and brand together in a website that is straightforward to maintain. We plan reusable page structures and editing tools around the people who will manage your site.',details:['Build a theme around your content, visual identity, and core page types.','Provide practical guidance for updating pages, media, and menus.','Review plugin requirements and identify avoidable complexity before launch.','Map existing content and redirects so a move to WordPress is carefully planned.'],need:'Need a WordPress website for your business?'},
 shopify:{headline:'Build a Shopify store around the way you sell.',intro:'Your store should express your brand and make everyday retail tasks easier. We bring your products, collections, and content into a coherent Shopify shopping experience.',details:['Adapt your storefront layout, styling, and content to your brand.','Structure collections and navigation around how customers discover your products.','Review payment, delivery, and tax configuration requirements with your team.','Explain the product, order, and content workflows you will use after handover.'],need:'Ready for a better Shopify store?'},
 'custom-applications':{headline:'Software built around your real working day.',intro:'When disconnected tools create extra work, a focused application can bring the process together. We begin with the tasks, permissions, and information your team needs to work confidently.',details:['Map real tasks and identify where information gets lost or duplicated.','Test the main screens and interactions before committing to the full build.','Define how data will move between your application and connected tools.','Plan who can view, create, approve, and manage different records.'],need:'Need an application that fits your workflow?'},
 'seo-and-search-visibility':{headline:'Help customers find the answers your business offers.',intro:'Useful search visibility depends on clear content and a sound technical foundation. We look at how people search, what your pages explain, and what may be preventing discovery.',details:['Review crawlability, indexing signals, page structure, and technical priorities.','Plan accurate local listings and location content for the areas you serve.','Connect useful pages and topics to the questions your customers ask.','Explore structured, answer-focused content without promising rankings or AI placement.'],need:'Want a clearer plan for search visibility?'},
 'paid-advertising':{headline:'Give every campaign a clear purpose.',intro:'Paid campaigns work best when the offer, audience, landing page, and measurement agree. We shape a practical test plan around your goals and a budget you control.',details:['Plan search or shopping activity around relevant customer intent.','Develop audience and creative tests suited to your offer and channel.','Align campaign messages with pages that explain the next step clearly.','Agree which actions to measure and how results will inform the next review.'],need:'Ready to plan your next campaign?'},
 'social-media':{headline:'A consistent presence with something worth saying.',intro:'Good social content starts with an understanding of your customers and your voice. We turn useful ideas into a manageable publishing plan across the channels that fit your business.',details:['Plan themes, formats, and publishing priorities in an agreed calendar.','Set a clear tone and an approach to replies, questions, and escalation.','Create a recognisable visual direction for your campaign content.','Assess relevant partnerships, content requirements, and approval processes.'],need:'Need a more consistent social presence?'},
 'branding-and-graphic-design':{headline:'Make your business recognisable at every touchpoint.',intro:'A useful identity goes beyond a logo. We explore your positioning, visual language, and everyday materials so the brand can be applied consistently by your team.',details:['Develop a visual direction and logo system that reflect your business.','Bring the identity into proposals, business cards, and company materials.','Plan packaging artwork around product information and production requirements.','Document logo use, colours, typography, and practical examples.'],need:'Ready to give your brand a clear identity?'},
 'content-writing':{headline:'Explain your value in words your customers understand.',intro:'Clear writing helps people make informed decisions. We shape your website and marketing copy around real questions, useful information, and a consistent British English tone.',details:['Structure service and page copy around your audience and the next action.','Turn product features into accurate, helpful descriptions.','Develop articles with a clear purpose, useful structure, and checked source material.','Agree your voice, terminology, and review process for future content.'],need:'Need clearer content for your business?'},
 'photography-and-video':{headline:'Show the details that make your business different.',intro:'The right images and footage make your products, spaces, and people easier to understand. We plan the story and the required formats before capture begins.',details:['Agree a shot list, locations, styling, and the intended use of the material.','Capture a consistent view of your products and their important details.','Plan footage and edits for your website and social channels.','Assess location permissions, conditions, and appropriate aerial capture options.'],need:'Ready to bring your business into focus?'},
 'virtual-tours':{headline:'Let people explore your space before they arrive.',intro:'A virtual tour should help visitors understand a location and make a more confident enquiry. We plan the route, capture requirements, and supporting information around the space.',details:['Choose viewpoints and routes that give a useful understanding of the location.','Prepare an interactive experience with clear movement between views.','Add relevant descriptions and points of interest at the right locations.','Plan responsive website placement and check the visitor journey.'],need:'Want to open your doors with a virtual tour?'},
 'hosting-and-domains':{headline:'Give your online presence a considered foundation.',intro:'Your website, domain, and business email need a setup that is clear to manage. We help identify requirements, ownership, access, and the support responsibilities involved.',details:['Review domain choices, ownership, renewal dates, and access arrangements.','Match hosting requirements to your site, traffic expectations, and maintenance plan.','Plan mailboxes and the records needed for your chosen email provider.','Configure encrypted website access and identify certificate renewal responsibilities.'],need:'Need help with hosting and domains?'},
 'maintenance-and-support':{headline:'Keep your website useful as your business changes.',intro:'Website care is easier when responsibilities and priorities are clear. We plan routine checks, updates, and support around your platform and the changes you expect to make.',details:['Agree a practical update schedule and a way to review changes safely.','Define backup frequency, retention, and how recovery will be checked.','Review speed and usability issues and prioritise meaningful improvements.','Set the request process, scope, and response expectations before support begins.'],need:'Need dependable website care?'},
 'telecom-and-voip':{headline:'Make it easier for customers to reach the right person.',intro:'A good phone setup follows the way your team actually works. We review call journeys, availability, and administration before recommending a configuration.',details:['Map incoming calls, transfers, out-of-hours handling, and escalation paths.','Review provider, connection, and system requirements for your team.','Plan queues and routing around availability and customer needs.','Provide guidance for everyday use and the people administering the system.'],need:'Ready to improve your business calls?'},
 'infrastructure-support':{headline:'A clearer foundation for the tools your team relies on.',intro:'Your infrastructure should support everyday work and leave room to adapt. We assess dependencies, access, and recovery priorities before proposing changes.',details:['Review the network setup and identify practical reliability priorities.','Assess cloud requirements, access, and dependencies around your workflows.','Identify useful monitoring signals and who should respond to them.','Document recovery steps, responsibilities, and the checks needed to test them.'],need:'Need a clearer infrastructure plan?'},
 'platform-development':{headline:'Choose a platform that fits your business and your team.',intro:'The right platform depends on what you publish, sell, and maintain. We compare your requirements with the tools your team will use after the build.',details:['Review WordPress-based commerce requirements and catalogue workflows.','Assess managed site-builder options against your content and editing needs.','Explore visual publishing and reusable content structures for your website.','Map content, redirects, assets, and launch responsibilities before a move.'],need:'Need help choosing your next website platform?'},
 'business-systems':{headline:'Bring your business processes into one clear workflow.',intro:'Internal systems should make work easier to follow. We turn operational requirements into a practical scope, with attention to users, records, approvals, and reporting.',details:['Map customer and operational records and how teams need to use them.','Plan learning or marketplace journeys around users and transactions.','Define billing and project workflows with useful ownership and reporting.','Document recruitment or voting requirements, access boundaries, and audit needs.'],need:'Ready to simplify a business process?'},
 'extensions-and-integrations':{headline:'Connect your tools without adding unnecessary steps.',intro:'Useful integrations move the right information at the right time. We start with the source of truth, access requirements, and what should happen when a connection fails.',details:['Identify the WordPress functionality you need and how it will be maintained.','Review Shopify app requirements, permissions, and operational impact.','Adapt the presentation layer while keeping the platform workflow clear.','Define data mappings, error handling, and testing for connected systems.'],need:'Need your business tools to work together?'},
 'digital-growth-partnership':{headline:'Bring your website, content, and campaigns into one plan.',intro:'A shared roadmap helps avoid disconnected activity. We agree priorities, coordinate the work, and review useful measures as your business requirements evolve.',details:['Agree a realistic sequence of work and what success should look like.','Connect storefront experience, brand presentation, and customer information.','Coordinate creative, messaging, and landing pages around agreed campaigns.','Review evidence and record what to keep, improve, or test next.'],need:'Ready for a more connected growth plan?'},
 'ai-assisted-experiences':{headline:'Use automation where it helps people do better work.',intro:'AI features need a clear job, appropriate data access, and human oversight. We explore bounded use cases before deciding what deserves a working prototype.',details:['Identify a focused task and the limits an automated assistant should respect.','Design assistance around information users need and actions they can review.','Test representative examples, failure cases, and the quality of the responses.','Review data access, retention expectations, and the need for human approval.'],need:'Have a useful automation idea in mind?'},
 'laravel-custom-website-development':{headline:'Build a Laravel platform around your business logic.',intro:'Complex journeys need a clear structure. We work through the records, roles, and integrations behind your platform before turning them into a usable web experience.',details:['Map business rules, user journeys, and the information each step requires.','Define application structure and the boundaries between core features.','Design account areas, forms, and administrative workflows around real tasks.','Plan connected services, data exchange, and how failures will be handled.'],need:'Need a custom Laravel platform?'},
 'website-redesign-and-development':{headline:'Keep what works. Improve what gets in the way.',intro:'A redesign should solve a problem, not simply change the colours. We review your content, journeys, and platform before creating a plan for a more useful website.',details:['Review existing pages and decide what to keep, combine, or rewrite.','Simplify navigation and enquiry paths around your audience’s priorities.','Plan redirects, content transfer, and checks before switching to the new site.','Identify performance bottlenecks and agree measurable improvements to pursue.'],need:'Is your website ready for a fresh start?'},
 photography:{headline:'An image library that tells your business story.',intro:'Strong photography starts with a clear purpose. We plan the subjects, visual direction, and intended use so your final selection works together across your website and marketing.',details:['Agree mood, framing, styling, and the visual language of the shoot.','Plan images that show product materials, scale, and important details.','Capture the people, spaces, and moments that support your brand story.','Select and refine images, then prepare agreed formats for their intended use.'],need:'Need photography that feels like your brand?'},
 videography:{headline:'Turn your story into a film people can follow.',intro:'A useful film combines a clear message, purposeful footage, and a considered edit. We plan the audience, channels, and key moments before production.',details:['Shape a narrative that explains the people and purpose behind your business.','Plan product or campaign films around the message and intended audience.','Prepare channel-appropriate edits, pacing, and aspect ratios.','Agree which moments to capture and how the finished footage will be used.'],need:'Ready to tell your story through video?'},
 'video-editing':{headline:'Make your footage tell a clearer story.',intro:'Editing gives raw material a direction. We organise the footage around the message, refine the pacing, and prepare exports suited to the channels you use.',details:['Build a clear sequence and choose the moments that carry the message.','Bring shots into a consistent, considered visual treatment.','Balance dialogue, music, and effects for a more comfortable listening experience.','Prepare readable captions and agreed formats for each delivery channel.'],need:'Need a sharper edit for your footage?'},
};

export function detailFor(service:Service){
 const editorial=serviceEditorial[service.slug];
 if(!editorial)throw new Error('Missing service editorial: '+service.slug);
 const category=serviceCategories.find(c=>c.title===service.group)!;
 const web=service.group==='Web Design & Development';
 const visual=service.group==='Videography & Photography';
 const brand=service.group==='Brand & Content';
 const support=web?{title:'Monthly website care',description:'A maintenance scope shaped around your platform, content, and ongoing priorities.',items:['Update planning','Backup checks','Performance reviews','Content changes','Issue triage','Handover guidance']}:
 visual?{title:'Ongoing creative production',description:'Plan the next shoot or edit with a consistent direction and agreed delivery formats.',items:['Production planning','Asset organisation','New edits','Format adaptation','Caption updates','Creative reviews']}:
 brand?{title:'Ongoing brand and content support',description:'Keep your identity, messaging, and campaign material consistent as your business develops.',items:['Content planning','Brand consistency','Creative updates','Editorial reviews','Campaign coordination','Progress reviews']}:
 {title:'Ongoing technology support',description:'Define a practical support scope for your systems, connections, and operational priorities.',items:['System reviews','Access checks','Update planning','Integration checks','Issue triage','Documentation']};
 return {...editorial,category,web,support,features:[...service.items.map((title,i)=>({title,description:editorial.details[i]})),{title:'A clear handover and next step',description:visual?'Receive the agreed assets, delivery formats, and usage information, with further edits scoped clearly.':brand?'Receive the agreed creative files, guidance, and a practical plan for keeping the work consistent.':'Agree documentation, ownership, and support responsibilities before handover.'}]};
}
